### ISSUE TITLE
has no exported member

### ISSUE THREAD

**Issue by yusufskebbe** [kapilkumar0037/country-library-usecases#1]
Hi, after I install the npm package and build my project, I get many errors about has no exported member.

Those are the errors 

**ModelSignal
InputSignal
OutputEmitterSignalRef**

**Comment by kapilkumar0037** [comment]
Hi @yusufskebbe, if you are cloning the project and running 'npm install' please remove '^' from  "ngx-countries-dropdown": "^1.0.4", package. After that it should work fine. 
though i will push the latest changes after upgrading to Angular 17 and using latest version of 'ngx-countries-dropdown'
Thanks,
Kapil
